exp_config:
  project: CLFDD
  exp_name: lbrclfdd-rat-200-60-nozca-cropfliprotate-10ipc
  seed: 0
  use_wandb: True
  wandb_api_key: 
  num_steps: 60000
  device: 'cuda'

dataset_config:
  dataset_name: cifar10
  data_path: /data/tfliu/dataset
  zca: False

eval_config:
  eval_interval: 100
  num_eval: 3
  eval_models:
    conv3:
      model_args:
        modelname: convnet3
      opt_args:
        opt_name: 'adam'
        lr: 0.001
  eval_steps: 1000
  test_module_args:
    module_name: clfmodule
    module_args:
      aug_args:
        strategy: ''
  upload_visualize: True
  upload_visualize_interval: 100
  save_visualize: True
  save_visualize_interval: 100

synset_config:
  synset_type: imagelabelersynset
  synset_args: 
    ipc: 10
    labeler_args:
      modelname: 'convnet3'
    labeler_path: './assets/conv3_stdt.pt'
    train_images: True
    images_opt_args:
      opt_name: adam
      lr: 1000
    train_labeler: False
    labeler_opt_args:
      opt_name: adam
      lr: 0.0001
    init_type: 'noise_normal'
    augment_args:
      strategy: 'crop_flip_rotate'
      batch: True

dd_config:
  bptt_type: rat_bptt
  num_forward: 200
  num_backward: 60
  ema_grad_clip: True
  ema_coef: 0.9
  meta_loss_batchsize: 1024
  ddalg_config:
    ddalg_type: clfdd
    ddalg_args:
      inner_module_args:
        module_name: clfmodule
        module_args:
          aug_args:
            strategy: ''
      external_module_args:
        module_name: clfmodule
        module_args:
          aug_args:
            strategy: 'crop_flip_rotate'
      inner_model_args:
        modelname: 'convnet3'
      inner_opt_args:
        opt_name: adam
        lr: 0.001
      inner_batch_size: 100
      data_per_loop: 6144
